#! /bin/bash

echo "Removing AppImageLauncher as interpreter for AppImages"

UPDATE_BINFMTS=update-binfmts

# TODO: configure the prefix path with CMake
if ! (type "$UPDATE_BINFMTS" 2>&1 1>/dev/null) && ! (which "$UPDATE_BINFMTS" 2>&1 1>/dev/null); then
    UPDATE_BINFMTS=/usr/lib/appimagelauncher/update-binfmts
fi

# TODO: configure the prefix path with CMake
(set -x; "$UPDATE_BINFMTS" --package appimage --remove appimage-type2 /usr/bin/AppImageLauncher)
