#! /bin/bash

echo "Installing AppImageLauncher as interpreter for AppImages"

(set -x; update-binfmts --package appimage --install appimage-type2 /usr/bin/AppImageLauncher --magic 'AI\x02' --offset 8)
