#! /bin/bash

echo "Removing AppImageLauncher as interpreter for AppImages"

set -x
update-binfmts --package appimage --remove appimage-type2 /usr/bin/AppImageLauncher
update-mime-database /usr/share/mime
