FROM i386/ubuntu:bionic

ENV ARCH=i386 DIST=bionic BUILD_LITE=1 CI=1

COPY ./install-deps.sh /
RUN bash -xe install-deps.sh

ENTRYPOINT ["/bin/bash", "-c", "set -x && source /opt/qt*/bin/qt*env.sh || true && export QT_SELECT=5 && exec \"$0\" \"$@\""]

# create unprivileged user for non-build-script use of this image
# build-in-docker.sh will likely not use this one, as it enforces the caller's uid inside the container
RUN adduser --system --group build
USER build
