FROM ubuntu:bionic

ENV ARCH=x86_64 DIST=bionic BUILD_LITE=1 CI=1

COPY ./install-deps.sh /
RUN bash -xe install-deps.sh

ENTRYPOINT ["/bin/bash", "-c", "set -x && source /opt/qt*/bin/qt*env.sh || true && export QT_SELECT=5 && exec \"$0\" \"$@\""]
