# used to cache installed dependencies for bionic builds
# this speeds up builds during development, as the dependencies are just installed _once_

FROM i386/ubuntu:bionic

RUN dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get -y --no-install-recommends install software-properties-common && \
    add-apt-repository -y ppa:beineri/opt-qt-5.12.3-bionic && \
    apt-get update && \
    apt-get -y --no-install-recommends install \
        qt512-meta-minimal:i386 \
        libfuse2:i386 \
        qtbase5-dev-tools \
        libqt5core5a:i386 \
        libqt5gui5:i386 \
        libcurl4-openssl-dev:i386 \
        libssl-dev:i386 \
        libqt5widgets5:i386 \
        librsvg2-bin:i386 \
        libfuse-dev:i386 \
        libcurl4:i386 \
        libcurl4 \
        libbsd-dev:i386 \
        libglib2.0-dev:i386 \
        liblzma-dev:i386 \
        libgtest-dev \
        libcairo-dev:i386 \
        libgl1-mesa-dev:i386 \
        libglu1-mesa-dev:i386 \
        \
        rpm \
        gcc-multilib \
        g++-multilib \
        cmake \
        make \
        git \
        ca-certificates \
        automake \
        autoconf \
        libtool \
        patch \
        wget \
        vim-common \
        desktop-file-utils \
        pkg-config \
        qttools5-dev-tools:i386 \
        libfontconfig1-dev:i386 \
        libfreetype6-dev:i386 \
        libarchive-dev:i386 \
        libboost-filesystem-dev:i386 \
        zlib1g:i386 \
        librsvg2-dev:i386

# https://github.com/TheAssassin/AppImageLauncher/issues/199
RUN bash -xc "apt-get update && \
    apt-get -y install libgtk2.0-dev:i386 libgl1-mesa-dev:i386 && \
    source /opt/qt*/bin/qt*env.sh && \
    git clone http://code.qt.io/qt/qtstyleplugins.git && \
    cd qtstyleplugins && \
    qmake && \
    make -j$(nproc) && \
    make install"

ENTRYPOINT ["/bin/bash", "-c", "set -x && . /opt/qt*/bin/qt*env.sh && export QT_SELECT=5 && exec \"$0\" \"$@\""]
