name: Continuous builds

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - NAME: bionic x86_64
            ARCH: x86_64
            DIST: bionic
          - NAME: bionic i386
            ARCH: i386
            DIST: bionic
          - NAME: bionic arm64
            ARCH: arm64
            DIST: bionic
          - NAME: bionic armhf
            ARCH: armhf
            DIST: bionic
          - NAME: Lite AppImage bionic x86_64
            ARCH: x86_64
            DIST: bionic
            BUILD_LITE: 1
          - NAME: Lite AppImage bionic i386
            ARCH: i386
            DIST: bionic
            BUILD_LITE: 1

    name: ${{ matrix.NAME }}
    env:
      ARCH: ${{ matrix.ARCH }}
      DIST: ${{ matrix.DIST }}
      BUILD_LITE: ${{ matrix.BUILD_LITE }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up QEMU integration for Docker
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Build in Docker
        run: bash -ex ci/build-in-docker.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: |
              appimagelauncher*.deb*
              appimagelauncher*.rpm*
              appimagelauncher*.tar*
              appimagelauncher-lite-*.AppImage*

  upload:
    name: Create release and upload artifacts
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.7
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WEBDAV_URL: ${{ secrets.WEBDAV_URL }}
          WEBDAV_USER: ${{ secrets.WEBDAV_USER }}
          WEBDAV_PASSWORD: ${{ secrets.WEBDAV_PASSWORD }}
        run: |
            env | grep GITHUB_ | grep -v GITHUB_TOKEN
            wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
            chmod +x pyuploadtool-x86_64.AppImage
            ./pyuploadtool-x86_64.AppImage **/appimagelauncher*.{deb,rpm,tar*,AppImage*}
